# -*- coding: utf-8 -*-
"""BankDatabaseProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gIMOdFr5hDArNQvoXxX8W1n8hxa8hS2Z
"""

import pymongo
from pymongo import MongoClient
import random
from random import randint

client = pymongo.MongoClient("mongodb+srv://Harsha123:Harshads17@cluster0.br6du.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.BankDatabase
records = db.accounts
print("Please choose an option from below")
print("Create a New Account: 1 \n" "Deposit Amount: 2 \n" "Withdraw Amount: 3 \n" "Check Balance: 4")
def randomnumber(N):
  minimum = pow(10, N-1)
  maximum = pow(10, N) - 1
  return random.randint(minimum,maximum)
choice = int(input()) 
if choice == 1:
  n = input("Enter the name: ")
  e = input("Enter the E-mail ID: ")
  a = int(input("Enter the Aadhar number: "))
  p = input("Enter the PAN number: ")
  print("Please choose the type of account:")
  print("Savings Account: 1 \n" "Current Account: 2 \n" "Fixed Deposit: 3")
  tac = int(input())
  if tac == 1:
    typac = "Savings Account"
  elif tac == 2:
    typac = "Current Account"
  elif tac == 3:
    typac = "Fixed Deposit"  
  acc = randomnumber(10)
  cid = n+"_123" 
  print("Account is created")
  print("Account Number: ", acc)
  print("Customer_id: ", cid)
  my_account = { "Customer-id": cid, 'Name': n, "Account": {"Account Number": acc, 'E-mail ID': e, 'Aadhar Number': a, "PAN number": p, "Type of Account": typac, "Balance": 0.0}}
  print(records.insert_one(my_account))

if choice == 2:
  depcid = input("Enter the customer id: ")
  depbal = float(input("Enter the amount to be deposited: "))
  myquery = {"Customer-id": depcid}
  newvalues = {'$inc':{"Account.Balance": depbal}}
  print("Amount is Deposited")
  print(records.update_one(myquery,newvalues))
  mydoc = records.find(myquery,{"_id":0,"Account.Balance":1})
  for x in mydoc:
    print(x)

if choice == 3:
  witcid = input("Enter the customer id: ")
  witbal = float(input("Enter the withdrawal amount: "))
  myquery = {"Customer-id": depcid}
  newvalues = {'$inc':{"Account.Balance": -witbal}}
  print("Amount withdrawn: ",witbal)
  print(records.update_one(myquery,newvalues))
  mydoc = records.find(myquery,{"_id":0,"Account.Balance":1})
  for x in mydoc:
    print(x)

if choice == 4:
  chkbal = input("Enter the customer id: ")
  myquery = {"Customer-id": chkbal}
  mydoc = records.find(myquery,{"_id":0,"Customer-id":1,"Name":1,"Account.Account Number":1,"Account.Type of Account": 1,"Account.Balance":1})
  for x in mydoc:
    print(x)